---
title: "Linear models"
author: "Amanda Chaves"
date: "2026-03-26"
output:
  html_document:
  md_document:
---

[GitHub link](https://github.com/Matioli-amoc/PLPA6820-Amanda.git)

```{r}
data("mtcars")

library(ggplot2)

ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_smooth(method = lm, se = FALSE, color = "grey") +
  geom_point(aes(color = wt)) +
  xlab("Weight") + 
  ylab("Miles per gallon") +
  scale_colour_gradient(low = "forestgreen", high = "black") +
  theme_classic()

lm1 <- lm(mpg ~ wt, data = mtcars)
summary(lm1)

anova(lm1)
cor.test(mtcars$wt, mtcars$mpg)

```

```{r}
ggplot(lm1, aes(y= .resid, x = .fitted)) +
  geom_point()+
  geom_hline(yintercept = 0)
```

```{r}
bull.rich <- read.csv("Bull_richness.csv")

library(tidyverse)
sub.bull.rich <- bull.rich%>%
  filter(GrowthStage == "V8" & Treatment == "Conv.")

t.test(richness ~ Fungicide, data = sub.bull.rich)


```
```{r}
summary(lm(richness ~ Fungicide, dat = sub.bull.rich))
```
```{r}
anova(lm(richness ~ Fungicide, data = sub.bull.rich))

```

```{r}
bull.rich.sub2 <- bull.rich %>%
  filter(Fungicide == "C" & Treatment == "Conv." & Crop == "Corn")

ggplot(bull.rich.sub2, aes(x = GrowthStage, y = richness))+
  geom_boxplot()

```

```{r}
summary(lm(richness ~ GrowthStage, dat = bull.rich.sub2))
```

```{r}
library(emmeans)
library(multcompView)
#install.packages("multcomp")
#sessionInfo()

lm3 <- lm(richness ~ GrowthStage, dat = bull.rich.sub2)

lsmeans <- emmeans(lm3, ~ GrowthStage)
lsmeans
```

```{r}
#results_lsmeans <- cld(lsmeans, alpha = 0.05, details = TRUE)
```

```{r}
library(tidyverse)
bull.rich.sub3 <- bull.rich %>%
  filter(Treatment == "Conv." & Crop == "Corn")

lm.interaction <- lm(richness ~ GrowthStage*Fungicide, data = bull.rich.sub3)
summary(lm.interaction)
anova(lm.interaction)


```

```{r}
lsmeans <- emmeans(lm.interaction, ~ Fungicide|GrowthStage)
#results_lsmeans <- cld(lsmeans, alpha = 0.05, deatils = TRUE)

ggplot(bull.rich.sub3, aes(x = GrowthStage, y = richness, colour = Fungicide))+
  geom_boxplot()
```

```{r}
library(lme4)

lm.interaction2 <- lmer(richness ~ GrowthStage*Fungicide + (1|Rep), data = bull.rich.sub3)
summary(lm.interaction2)
```

```{r}
summary(lm.interaction)
```

```{r}
lsmeans <- emmeans(lm.interaction2, ~ Fungicide|GrowthStage)
#results_lsmeans <- cld(lsmeans, alpha = 0.05, deatils = TRUE)
```






